# Generated by Django 3.0.7 on 2020-07-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='City Address', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'City Addresses',
            },
        ),
        migrations.CreateModel(
            name='CountryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Country Address', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Country Addresses',
            },
        ),
        migrations.CreateModel(
            name='PickupAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Pickup Address', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Pickup Addresses',
            },
        ),
        migrations.CreateModel(
            name='ProvinceAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Province Address', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Province Addresses',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Site Name', max_length=255)),
                ('site_logo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('main_header_logo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('site_title', models.CharField(default='Site Title', max_length=255)),
                ('site_sub_title', models.CharField(default='Site Sub Title', max_length=255)),
                ('header_text', models.TextField(default='Insert Header Text Here', max_length=1000)),
                ('header_logo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('header_logo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('phone', models.CharField(default='', max_length=55)),
                ('email', models.EmailField(default='', max_length=55)),
                ('location', models.CharField(default='', max_length=100)),
                ('office_hours', models.CharField(default='', max_length=100)),
                ('highlight_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('highlight_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('highlight_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('highlight_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('highlight_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('highlight_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('shop_spiel_title', models.CharField(default='Insert Spiel Title Here', max_length=55)),
                ('shop_spiel_text', models.TextField(default='Insert Spiel Text Here', max_length=4000)),
                ('about_sub_header', models.CharField(default='Insert Sub Header Here', max_length=55)),
                ('about_text', models.TextField(default='Insert About Text Here', max_length=4000)),
                ('standard_delivery_price', models.PositiveIntegerField(default=50)),
                ('express_delivery_price', models.PositiveIntegerField(default=150)),
                ('express_delivery_enabled', models.BooleanField(default=True)),
                ('standard_delivery_enabled', models.BooleanField(default=True)),
                ('pickup_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
