# Generated by Django 3.0.7 on 2020-08-07 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='main_header_logo',
            new_name='main_header_image',
        ),
    ]
