# Generated by Django 3.0.7 on 2020-08-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20200807_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='beta_mode',
            field=models.BooleanField(default=False),
        ),
    ]
