# Generated by Django 3.0.7 on 2020-08-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_siteconfiguration_beta_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_message',
            field=models.CharField(default='Welcome to Quezon Agrimart!', max_length=55),
        ),
    ]
