# Generated by Django 3.0.7 on 2020-08-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_auto_20200810_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_message',
            field=models.CharField(blank=True, default='Welcome to Quezon Agrimart!', max_length=125, null=True),
        ),
    ]
