# Generated by Django 3.0.7 on 2020-10-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_auto_20200810_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='express_delivery_enabled',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='express_delivery_price',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='pickup_enabled',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='standard_delivery_enabled',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='standard_delivery_price',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='per_km_price',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
