# Generated by Django 3.0.7 on 2021-01-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_auto_20201024_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='shipping_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
