# Generated by Django 3.0.7 on 2020-10-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='address',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='longitude',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
