# Generated by Django 3.0.7 on 2020-10-25 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_auto_20201025_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='height',
        ),
        migrations.RemoveField(
            model_name='order',
            name='length',
        ),
        migrations.RemoveField(
            model_name='order',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='order',
            name='width',
        ),
    ]
