# Generated by Django 3.0.7 on 2020-10-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_auto_20201025_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
