# Generated by Django 3.0.7 on 2020-10-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='latitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='longitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
