# Generated by Django 3.0.7 on 2020-10-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_auto_20201025_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='distance_value',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='duration_value',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
