# Generated by Django 3.0.7 on 2020-10-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_auto_20201026_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_validity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
