# Generated by Django 3.0.7 on 2020-10-29 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_auto_20201029_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='date_created',
        ),
    ]
