# Generated by Django 3.0.7 on 2020-11-28 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_remove_favorite_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='categorygroup',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='logistics.Seller'),
            preserve_default=False,
        ),
    ]
