# Generated by Django 3.0.7 on 2020-11-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_auto_20201128_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_pickedup',
            new_name='date_prepared',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_claimed',
            new_name='date_processed',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='is_pickedup',
            new_name='is_prepared',
        ),
        migrations.RemoveField(
            model_name='order',
            name='auth_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='capture_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_canceled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rider',
        ),
        migrations.AddField(
            model_name='order',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
