# Generated by Django 3.0.7 on 2020-11-28 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_auto_20201128_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='date_pickedup',
            new_name='date_prepared',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='is_pickedup',
            new_name='is_prepared',
        ),
    ]
