# Generated by Django 3.0.7 on 2020-12-13 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0018_seller_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='orders',
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
