# Generated by Django 3.0.7 on 2021-06-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0019_auto_20201213_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_canceled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
