# Generated by Django 3.0.7 on 2021-06-13 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0020_auto_20210612_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('reusable', models.BooleanField(default=False)),
                ('delivery_discount', models.DecimalField(decimal_places=2, default=0.1, max_digits=30)),
                ('order_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('affiliate_commission', models.DecimalField(decimal_places=2, default=0.1, max_digits=30)),
                ('rider_commission', models.DecimalField(decimal_places=2, default=0.1, max_digits=30)),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('affiliate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
