# Generated by Django 3.0.7 on 2020-10-21 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_facebook_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_region',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_zipcode',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=91)),
                ('longitude', models.CharField(max_length=91)),
                ('address', models.CharField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
