# Generated by Django 3.0.7 on 2021-06-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0021_promocode'),
        ('accounts', '0004_address_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='promo_codes_used',
            field=models.ManyToManyField(blank=True, to='logistics.PromoCode'),
        ),
    ]
